
package com.sf.integration.expressservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://service.expressservice.integration.sf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sfexpressService", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.service.SfexpressService")
    @ResponseWrapper(localName = "sfexpressServiceResponse", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.service.SfexpressServiceResponse")
    public String sfexpressService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
